PREFIX    = /usr/local
MANPREFIX = $(PREFIX)/share/man

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -DUSE_ADJTIMEX
CFLAGS   = -std=c99 -Wall -Wextra -O2
LDFLAGS  = -s
